package gui;

import Data.Clases.Configuracion;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 * Ventana desde la que se puede cambiar la configuración de variables 
 * globales en la aplicación que están almacenadas en la base de datos.
 *
 * @author Víctor Martín Torres - 12/06/2018
 * @see Configuracion
 */
public class FrmConfig extends javax.swing.JFrame 
{
    private ArrayList<Configuracion> _aConfig;
    private JLabel _lblNombreTienda;
    
    /**
     * Crea un nuevo formulario de configuracion.
     * @param lblNombreTienda Es necesario que se le pase el JLabel que contiene
     * el nombre de la tienda de la ventana principal para poder cambiar su 
     * contenido sin tener que cerrarla.
     */
    public FrmConfig(JLabel lblNombreTienda) 
    {
        initComponents();
        
        _lblNombreTienda = lblNombreTienda;
        
        //Obtener todas las variables globales de configuración
        try {
            _aConfig = Configuracion.Select(null, null);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, 
                "Error al leer la configuración.\n"+ex.toString(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
        
        //Asignar sus valores a las cajas de texto
        txtNombreTienda.setText(_aConfig.get(0).getValor());
        txtEmail.setText(_aConfig.get(1).getValor());
    }
    
    /**
     * Personalizar el icono de la ventana
     * @return Devuelve el icono personalizado.
     */
    @Override
    public Image getIconImage() 
    {
       return Toolkit.getDefaultToolkit()
               .getImage(ClassLoader.getSystemResource("img/boton_48.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreTienda = new javax.swing.JLabel();
        txtNombreTienda = new javax.swing.JTextField();
        butGuardar = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuración");
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(400, 150));

        lblNombreTienda.setText("Nombre de la tienda:");

        butGuardar.setBackground(java.awt.Color.green);
        butGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        butGuardar.setText("Guardar y salir");
        butGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butGuardarActionPerformed(evt);
            }
        });

        lblEmail.setText("Email:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 261, Short.MAX_VALUE)
                        .addComponent(butGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreTienda)
                            .addComponent(lblEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreTienda)
                            .addComponent(txtEmail))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreTienda)
                    .addComponent(txtNombreTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butGuardar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butGuardarActionPerformed
        _lblNombreTienda.setText(txtNombreTienda.getText());
        _aConfig.get(0).setValor(txtNombreTienda.getText());
        _aConfig.get(1).setValor(txtEmail.getText());
        
        try{
            for(Configuracion c : _aConfig)
                c.Update();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, 
                "Error al guardar.\n"+ex.toString(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_butGuardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butGuardar;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNombreTienda;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombreTienda;
    // End of variables declaration//GEN-END:variables
}
