/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Data.Clases.Categoria;
import Data.Clases.Imagen;
import Data.Clases.Marca;
import Data.Modelos.ModArticulo_Color_Imagen;
import Data.Modelos.ModImagenes;
import Data.Renders.ListaImagenesRender;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author victor
 */
public class IfrImagenes_Articulo_Color extends javax.swing.JFrame {

    private ModArticulo_Color_Imagen _modArticulo_Color_Imagen = null;
    private Marca _marca;
    private Categoria _categoria;
    private JLabel _iconoImagen;
    private ModImagenes _modImagenes = new ModImagenes();
    public boolean bAbierto;
    
    /**
     * Creates new form IfrImagenes
     */
    public IfrImagenes_Articulo_Color(ModArticulo_Color_Imagen modArticulo_Color_Imagen) throws Exception {
        initComponents();
        
        _modArticulo_Color_Imagen = modArticulo_Color_Imagen;
        bAbierto = true;
        
        lImagenes.setModel(_modImagenes);
        lImagenes.setCellRenderer(new ListaImagenesRender());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lImagenes = new javax.swing.JList<>();
        butElegir = new javax.swing.JButton();
        butCancelar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Imágenes");
        setUndecorated(true);
        setResizable(false);

        lImagenes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lImagenes);

        butElegir.setText("Elegir");
        butElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butElegirActionPerformed(evt);
            }
        });

        butCancelar.setText("Cancelar");
        butCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(butElegir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butElegir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butCancelar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void butCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        bAbierto = false;
        this.dispose();
    }                                           

    private void butElegirActionPerformed(java.awt.event.ActionEvent evt) {                                          
        int iIndex = lImagenes.getSelectedIndex();
        if(iIndex != -1)
        {
            try {
                _modArticulo_Color_Imagen.addImagen(_modImagenes.getImagen(iIndex));
            } catch (Exception ex) {
                System.out.println("Error en la imagen. "+ ex.toString());
            }
        }
        
        bAbierto = false;
        this.dispose();
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IfrImagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IfrImagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IfrImagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IfrImagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new IfrImagenes().setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(IfrImagenes.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
*/
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton butCancelar;
    private javax.swing.JButton butElegir;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lImagenes;
    // End of variables declaration                   
}
